-- 在线问诊平台 - 缺失表创建脚本
-- 生成时间: 2026-05-10

-- 5.1.3 收货地址表
CREATE TABLE IF NOT EXISTS patient_address (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'address_id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    receiver_name VARCHAR(50) NOT NULL COMMENT 'receiver_name',
    receiver_phone VARCHAR(20) NOT NULL COMMENT 'receiver_phone',
    province VARCHAR(20) NOT NULL COMMENT 'province',
    city VARCHAR(20) NOT NULL COMMENT 'city',
    district VARCHAR(20) NOT NULL COMMENT 'district',
    detail_address VARCHAR(255) NOT NULL COMMENT 'detail_address',
    postal_code VARCHAR(10) DEFAULT NULL COMMENT 'postal_code',
    is_default TINYINT NOT NULL DEFAULT 0 COMMENT 'is_default:0-no 1-yes',
    address_tag VARCHAR(20) DEFAULT NULL COMMENT 'address_tag',
    longitude DECIMAL(10,7) DEFAULT NULL COMMENT 'longitude',
    latitude DECIMAL(10,7) DEFAULT NULL COMMENT 'latitude',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    KEY idx_is_default (user_id, is_default),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='patient_address';

-- 5.2.3 医生排班表
CREATE TABLE IF NOT EXISTS doctor_schedule (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'schedule_id',
    doctor_id BIGINT UNSIGNED NOT NULL COMMENT 'doctor_id',
    schedule_date DATE NOT NULL COMMENT 'schedule_date',
    time_slot_id INT NOT NULL COMMENT 'time_slot_id',
    time_slot_name VARCHAR(50) NOT NULL COMMENT 'time_slot_name',
    time_slot_start TIME NOT NULL COMMENT 'time_slot_start',
    time_slot_end TIME NOT NULL COMMENT 'time_slot_end',
    max_appointments INT NOT NULL DEFAULT 10 COMMENT 'max_appointments',
    used_appointments INT NOT NULL DEFAULT 0 COMMENT 'used_appointments',
    remaining_appointments INT NOT NULL DEFAULT 10 COMMENT 'remaining_appointments',
    price DECIMAL(10,2) NOT NULL COMMENT 'price',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:0-rest 1-available 2-full 3-closed',
    remark VARCHAR(255) DEFAULT NULL COMMENT 'remark',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_doctor_date_slot (doctor_id, schedule_date, time_slot_id),
    KEY idx_schedule_date (schedule_date),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='doctor_schedule';

-- 4.2.4 医生评价表
CREATE TABLE IF NOT EXISTS doctor_review (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'review_id',
    doctor_id BIGINT UNSIGNED NOT NULL COMMENT 'doctor_id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    inquiry_id BIGINT UNSIGNED NOT NULL COMMENT 'inquiry_id',
    rating TINYINT NOT NULL COMMENT 'rating 1-5',
    attitude_rating TINYINT DEFAULT NULL COMMENT 'attitude_rating 1-5',
    skill_rating TINYINT DEFAULT NULL COMMENT 'skill_rating 1-5',
    content TEXT DEFAULT NULL COMMENT 'content',
    images TEXT DEFAULT NULL COMMENT 'images json',
    is_anonymous TINYINT NOT NULL DEFAULT 0 COMMENT 'is_anonymous:0-no 1-yes',
    tags VARCHAR(255) DEFAULT NULL COMMENT 'tags',
    helpful_count INT NOT NULL DEFAULT 0 COMMENT 'helpful_count',
    reply TEXT DEFAULT NULL COMMENT 'reply',
    reply_time DATETIME DEFAULT NULL COMMENT 'reply_time',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:0-hidden 1-show',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    PRIMARY KEY (id),
    KEY idx_doctor_id (doctor_id),
    KEY idx_user_id (user_id),
    KEY idx_inquiry_id (inquiry_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='doctor_review';

-- 4.2.5 预约记录表
CREATE TABLE IF NOT EXISTS appointment (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'appointment_id',
    appointment_no VARCHAR(32) NOT NULL COMMENT 'appointment_no',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    doctor_id BIGINT UNSIGNED NOT NULL COMMENT 'doctor_id',
    schedule_id BIGINT UNSIGNED NOT NULL COMMENT 'schedule_id',
    department_id BIGINT UNSIGNED NOT NULL COMMENT 'department_id',
    appointment_date DATE NOT NULL COMMENT 'appointment_date',
    time_slot_id INT NOT NULL COMMENT 'time_slot_id',
    time_slot_name VARCHAR(50) NOT NULL COMMENT 'time_slot_name',
    start_time TIME NOT NULL COMMENT 'start_time',
    end_time TIME NOT NULL COMMENT 'end_time',
    patient_name VARCHAR(50) NOT NULL COMMENT 'patient_name',
    patient_phone VARCHAR(20) NOT NULL COMMENT 'patient_phone',
    patient_gender TINYINT DEFAULT NULL COMMENT 'patient_gender',
    patient_age TINYINT UNSIGNED DEFAULT NULL COMMENT 'patient_age',
    symptoms VARCHAR(500) DEFAULT NULL COMMENT 'symptoms',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait_pay 2-appointment 3-checkin 4-completed 5-cancelled 6-refunded',
    visit_status TINYINT NOT NULL DEFAULT 0 COMMENT 'visit_status:0-not 1-visited 2-skip',
    check_in_time DATETIME DEFAULT NULL COMMENT 'check_in_time',
    visit_time DATETIME DEFAULT NULL COMMENT 'visit_time',
    inquiry_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'inquiry_id',
    source VARCHAR(20) DEFAULT NULL COMMENT 'source:app/h5/miniapp/web',
    cancel_reason VARCHAR(255) DEFAULT NULL COMMENT 'cancel_reason',
    cancel_time DATETIME DEFAULT NULL COMMENT 'cancel_time',
    cancel_user_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'cancel_user_id',
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'total_amount',
    actual_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'actual_amount',
    payment_status TINYINT NOT NULL DEFAULT 0 COMMENT 'payment_status:0-wait 1-paid 2-refunded',
    payment_time DATETIME DEFAULT NULL COMMENT 'payment_time',
    payment_method VARCHAR(20) DEFAULT NULL COMMENT 'payment_method',
    transaction_id VARCHAR(64) DEFAULT NULL COMMENT 'transaction_id',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_appointment_no (appointment_no),
    KEY idx_user_status (user_id, status),
    KEY idx_doctor_date (doctor_id, appointment_date),
    KEY idx_status (status),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='appointment';

-- 4.4.2 处方药品明细表
CREATE TABLE IF NOT EXISTS prescription_drug (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'detail_id',
    prescription_id BIGINT UNSIGNED NOT NULL COMMENT 'prescription_id',
    drug_id BIGINT UNSIGNED NOT NULL COMMENT 'drug_id',
    drug_name VARCHAR(100) NOT NULL COMMENT 'drug_name',
    common_name VARCHAR(100) DEFAULT NULL COMMENT 'common_name',
    specification VARCHAR(100) DEFAULT NULL COMMENT 'specification',
    manufacturer VARCHAR(100) DEFAULT NULL COMMENT 'manufacturer',
    approval_no VARCHAR(50) DEFAULT NULL COMMENT 'approval_no',
    quantity INT NOT NULL COMMENT 'quantity',
    unit VARCHAR(20) NOT NULL COMMENT 'unit',
    price DECIMAL(10,2) NOT NULL COMMENT 'price',
    subtotal DECIMAL(10,2) NOT NULL COMMENT 'subtotal',
    `usage` VARCHAR(100) DEFAULT NULL COMMENT 'usage',
    dosage VARCHAR(100) DEFAULT NULL COMMENT 'dosage',
    frequency VARCHAR(50) DEFAULT NULL COMMENT 'frequency',
    duration VARCHAR(50) DEFAULT NULL COMMENT 'duration',
    total_days INT DEFAULT NULL COMMENT 'total_days',
    taking_method VARCHAR(50) DEFAULT NULL COMMENT 'taking_method',
    cautions TEXT DEFAULT NULL COMMENT 'cautions',
    side_effects TEXT DEFAULT NULL COMMENT 'side_effects',
    storage_condition VARCHAR(100) DEFAULT NULL COMMENT 'storage_condition',
    is_otc TINYINT NOT NULL DEFAULT 0 COMMENT 'is_otc:0-rx 1-otc',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'sort_order',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    PRIMARY KEY (id),
    KEY idx_prescription_id (prescription_id),
    KEY idx_drug_id (drug_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='prescription_drug';

-- 4.5.1 订单主表
CREATE TABLE IF NOT EXISTS medical_order (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'order_id',
    order_no VARCHAR(32) NOT NULL COMMENT 'order_no',
    order_type TINYINT NOT NULL COMMENT 'order_type:1-inquiry 2-drug 3-package 4-appointment',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    inquiry_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'inquiry_id',
    prescription_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'prescription_id',
    doctor_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'doctor_id',
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'total_amount',
    freight_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'freight_amount',
    discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount_amount',
    coupon_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'coupon_amount',
    integral_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'integral_amount',
    actual_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'actual_amount',
    pay_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'pay_amount',
    refund_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'refund_amount',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait_pay 2-paid 3-processing 4-completed 5-cancelled 6-refund 7-refunded',
    payment_method VARCHAR(20) DEFAULT NULL COMMENT 'payment_method',
    payment_time DATETIME DEFAULT NULL COMMENT 'payment_time',
    payment_trade_no VARCHAR(64) DEFAULT NULL COMMENT 'payment_trade_no',
    pay_deadline DATETIME DEFAULT NULL COMMENT 'pay_deadline',
    delivery_type TINYINT DEFAULT NULL COMMENT 'delivery_type:1-express 2-self 3-instant',
    address_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'address_id',
    receiver_name VARCHAR(50) DEFAULT NULL COMMENT 'receiver_name',
    receiver_phone VARCHAR(20) DEFAULT NULL COMMENT 'receiver_phone',
    receiver_address VARCHAR(255) DEFAULT NULL COMMENT 'receiver_address',
    express_company VARCHAR(50) DEFAULT NULL COMMENT 'express_company',
    express_no VARCHAR(50) DEFAULT NULL COMMENT 'express_no',
    delivery_time DATETIME DEFAULT NULL COMMENT 'delivery_time',
    receive_time DATETIME DEFAULT NULL COMMENT 'receive_time',
    invoice_type TINYINT DEFAULT NULL COMMENT 'invoice_type:0-no 1-personal 2-company',
    invoice_title VARCHAR(100) DEFAULT NULL COMMENT 'invoice_title',
    invoice_tax_no VARCHAR(50) DEFAULT NULL COMMENT 'invoice_tax_no',
    invoice_status TINYINT DEFAULT 0 COMMENT 'invoice_status:0-not 1-opened 2-shipped',
    remark VARCHAR(500) DEFAULT NULL COMMENT 'remark',
    cancel_reason VARCHAR(255) DEFAULT NULL COMMENT 'cancel_reason',
    cancel_time DATETIME DEFAULT NULL COMMENT 'cancel_time',
    cancel_user_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'cancel_user_id',
    source VARCHAR(20) DEFAULT NULL COMMENT 'source:app/h5/miniapp/web',
    coupon_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'coupon_id',
    use_integral INT DEFAULT 0 COMMENT 'use_integral',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_user_id (user_id),
    KEY idx_order_type (order_type),
    KEY idx_status (status),
    KEY idx_payment_status (status, payment_time),
    KEY idx_created_at (created_at),
    KEY idx_pay_deadline (pay_deadline),
    KEY idx_express_no (express_no),
    KEY idx_user_status (user_id, status),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='medical_order';

-- 5.5.2 订单明细表
CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'item_id',
    order_id BIGINT UNSIGNED NOT NULL COMMENT 'order_id',
    drug_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'drug_id',
    drug_name VARCHAR(100) NOT NULL COMMENT 'drug_name',
    common_name VARCHAR(100) DEFAULT NULL COMMENT 'common_name',
    specification VARCHAR(100) DEFAULT NULL COMMENT 'specification',
    manufacturer VARCHAR(100) DEFAULT NULL COMMENT 'manufacturer',
    approval_no VARCHAR(50) DEFAULT NULL COMMENT 'approval_no',
    image VARCHAR(255) DEFAULT NULL COMMENT 'image',
    quantity INT NOT NULL COMMENT 'quantity',
    price DECIMAL(10,2) NOT NULL COMMENT 'price',
    cost_price DECIMAL(10,2) DEFAULT NULL COMMENT 'cost_price',
    subtotal DECIMAL(10,2) NOT NULL COMMENT 'subtotal',
    prescription_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'prescription_id',
    is_gift TINYINT NOT NULL DEFAULT 0 COMMENT 'is_gift:0-no 1-yes',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    PRIMARY KEY (id),
    KEY idx_order_id (order_id),
    KEY idx_drug_id (drug_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='order_item';

-- 4.5.3 退款申请表
CREATE TABLE IF NOT EXISTS refund_apply (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'refund_id',
    apply_no VARCHAR(32) NOT NULL COMMENT 'apply_no',
    order_id BIGINT UNSIGNED NOT NULL COMMENT 'order_id',
    order_no VARCHAR(32) NOT NULL COMMENT 'order_no',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    refund_type TINYINT NOT NULL COMMENT 'refund_type:1-refund 2-refund_goods',
    refund_reason TINYINT NOT NULL COMMENT 'refund_reason',
    refund_amount DECIMAL(10,2) NOT NULL COMMENT 'refund_amount',
    approve_amount DECIMAL(10,2) DEFAULT NULL COMMENT 'approve_amount',
    refund_remark VARCHAR(500) DEFAULT NULL COMMENT 'refund_remark',
    images TEXT DEFAULT NULL COMMENT 'images json',
    video VARCHAR(255) DEFAULT NULL COMMENT 'video',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait 2-pass 3-reject 4-refunding 5-completed 6-cancelled',
    audit_user_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'audit_user_id',
    audit_time DATETIME DEFAULT NULL COMMENT 'audit_time',
    audit_remark VARCHAR(255) DEFAULT NULL COMMENT 'audit_remark',
    refund_time DATETIME DEFAULT NULL COMMENT 'refund_time',
    refund_trade_no VARCHAR(64) DEFAULT NULL COMMENT 'refund_trade_no',
    refund_channel VARCHAR(20) DEFAULT NULL COMMENT 'refund_channel',
    process_video VARCHAR(255) DEFAULT NULL COMMENT 'process_video',
    inquiry_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'inquiry_id',
    cancel_time DATETIME DEFAULT NULL COMMENT 'cancel_time',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_apply_no (apply_no),
    KEY idx_order_id (order_id),
    KEY idx_user_id (user_id),
    KEY idx_status (status),
    KEY idx_created_at (created_at),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='refund_apply';

-- 4.6.1 药品表
CREATE TABLE IF NOT EXISTS drug (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'drug_id',
    drug_name VARCHAR(100) NOT NULL COMMENT 'drug_name',
    common_name VARCHAR(100) DEFAULT NULL COMMENT 'common_name',
    english_name VARCHAR(100) DEFAULT NULL COMMENT 'english_name',
    pinyin VARCHAR(100) DEFAULT NULL COMMENT 'pinyin',
    specification VARCHAR(100) DEFAULT NULL COMMENT 'specification',
    unit VARCHAR(20) NOT NULL COMMENT 'unit',
    manufacturer VARCHAR(100) DEFAULT NULL COMMENT 'manufacturer',
    approval_no VARCHAR(50) DEFAULT NULL COMMENT 'approval_no',
    category_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'category_id',
    drug_type TINYINT NOT NULL COMMENT 'drug_type:1-rx 2-otc-a 3-otc-b',
    dosage_form VARCHAR(50) DEFAULT NULL COMMENT 'dosage_form',
    main_ingredients TEXT DEFAULT NULL COMMENT 'main_ingredients',
    indication TEXT DEFAULT NULL COMMENT 'indication',
    `usage` VARCHAR(200) DEFAULT NULL COMMENT 'usage',
    adverse_reaction TEXT DEFAULT NULL COMMENT 'adverse_reaction',
    contraindication TEXT DEFAULT NULL COMMENT 'contraindication',
    warning TEXT DEFAULT NULL COMMENT 'warning',
    drug_interaction TEXT DEFAULT NULL COMMENT 'drug_interaction',
    storage_condition VARCHAR(100) DEFAULT NULL COMMENT 'storage_condition',
    shelf_life INT DEFAULT NULL COMMENT 'shelf_life month',
    weight DECIMAL(8,2) DEFAULT NULL COMMENT 'weight g',
    image VARCHAR(255) DEFAULT NULL COMMENT 'image',
    images TEXT DEFAULT NULL COMMENT 'images json',
    video VARCHAR(255) DEFAULT NULL COMMENT 'video',
    price DECIMAL(10,2) NOT NULL COMMENT 'price',
    original_price DECIMAL(10,2) DEFAULT NULL COMMENT 'original_price',
    cost_price DECIMAL(10,2) DEFAULT NULL COMMENT 'cost_price',
    stock INT NOT NULL DEFAULT 0 COMMENT 'stock',
    reserved_stock INT NOT NULL DEFAULT 0 COMMENT 'reserved_stock',
    sales_count INT NOT NULL DEFAULT 0 COMMENT 'sales_count',
    view_count INT NOT NULL DEFAULT 0 COMMENT 'view_count',
    collection_count INT NOT NULL DEFAULT 0 COMMENT 'collection_count',
    prescription_required TINYINT NOT NULL DEFAULT 0 COMMENT 'prescription_required:0-no 1-yes',
    is_hot TINYINT NOT NULL DEFAULT 0 COMMENT 'is_hot:0-no 1-yes',
    is_recommend TINYINT NOT NULL DEFAULT 0 COMMENT 'is_recommend:0-no 1-yes',
    is_new TINYINT NOT NULL DEFAULT 0 COMMENT 'is_new:0-no 1-yes',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'sort_order',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:0-off 1-on 2-soldout 3-violation',
    audit_status TINYINT NOT NULL DEFAULT 1 COMMENT 'audit_status:0-wait 1-pass 2-reject',
    audit_remark VARCHAR(255) DEFAULT NULL COMMENT 'audit_remark',
    reject_reason VARCHAR(255) DEFAULT NULL COMMENT 'reject_reason',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    FULLTEXT KEY ft_drug_search (drug_name, common_name, pinyin),
    KEY idx_category_status (category_id, status),
    KEY idx_drug_type (drug_type),
    KEY idx_price_stock (price, stock),
    KEY idx_hot_recommend (is_hot, is_recommend),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='drug';

-- 5.6.2 药品分类表
CREATE TABLE IF NOT EXISTS drug_category (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'category_id',
    parent_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'parent_id',
    name VARCHAR(50) NOT NULL COMMENT 'name',
    icon VARCHAR(255) DEFAULT NULL COMMENT 'icon',
    banner VARCHAR(255) DEFAULT NULL COMMENT 'banner',
    description TEXT DEFAULT NULL COMMENT 'description',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'sort_order',
    level INT NOT NULL DEFAULT 1 COMMENT 'level',
    product_count INT NOT NULL DEFAULT 0 COMMENT 'product_count',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:0-disabled 1-enabled',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    KEY idx_parent_id (parent_id),
    KEY idx_sort_order (sort_order),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='drug_category';

-- 4.7.1 药师信息表
CREATE TABLE IF NOT EXISTS pharmacist (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'pharmacist_id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    pharmacist_no VARCHAR(20) NOT NULL COMMENT 'pharmacist_no',
    license_no VARCHAR(50) NOT NULL COMMENT 'license_no',
    license_img VARCHAR(255) DEFAULT NULL COMMENT 'license_img',
    license_start DATE DEFAULT NULL COMMENT 'license_start',
    license_end DATE DEFAULT NULL COMMENT 'license_end',
    pharmacy_name VARCHAR(100) DEFAULT NULL COMMENT 'pharmacy_name',
    pharmacy_address VARCHAR(255) DEFAULT NULL COMMENT 'pharmacy_address',
    professional_title VARCHAR(50) DEFAULT NULL COMMENT 'professional_title',
    specialty VARCHAR(200) DEFAULT NULL COMMENT 'specialty',
    introduction TEXT DEFAULT NULL COMMENT 'introduction',
    audit_count INT NOT NULL DEFAULT 0 COMMENT 'audit_count',
    audit_pass_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'audit_pass_rate',
    rating DECIMAL(3,2) NOT NULL DEFAULT 5.00 COMMENT 'rating',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:0-disabled 1-normal 2-wait 3-reject',
    reject_reason VARCHAR(255) DEFAULT NULL COMMENT 'reject_reason',
    audit_time DATETIME DEFAULT NULL COMMENT 'audit_time',
    audit_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'audit_user',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_id (user_id),
    UNIQUE KEY uk_pharmacist_no (pharmacist_no),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='pharmacist';

-- 4.8.1 投诉表
CREATE TABLE IF NOT EXISTS complaint (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'complaint_id',
    complaint_no VARCHAR(32) NOT NULL COMMENT 'complaint_no',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    target_type TINYINT NOT NULL COMMENT 'target_type:1-doctor 2-pharmacist 3-platform 4-pharmacy',
    target_id BIGINT UNSIGNED NOT NULL COMMENT 'target_id',
    target_name VARCHAR(50) DEFAULT NULL COMMENT 'target_name',
    type TINYINT NOT NULL COMMENT 'type',
    content TEXT NOT NULL COMMENT 'content',
    images TEXT DEFAULT NULL COMMENT 'images json',
    contact VARCHAR(50) DEFAULT NULL COMMENT 'contact',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait 2-processing 3-solved 4-closed',
    priority TINYINT NOT NULL DEFAULT 1 COMMENT 'priority:1-low 2-medium 3-high',
    handler_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'handler_id',
    handle_time DATETIME DEFAULT NULL COMMENT 'handle_time',
    handle_result TEXT DEFAULT NULL COMMENT 'handle_result',
    user_satisfaction TINYINT DEFAULT NULL COMMENT 'user_satisfaction 1-5',
    user_feedback TEXT DEFAULT NULL COMMENT 'user_feedback',
    close_time DATETIME DEFAULT NULL COMMENT 'close_time',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_complaint_no (complaint_no),
    KEY idx_user_id (user_id),
    KEY idx_target_type (target_type),
    KEY idx_target_id (target_id),
    KEY idx_status (status),
    KEY idx_priority (priority),
    KEY idx_handler_id (handler_id),
    KEY idx_created_at (created_at),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='complaint';

-- 5.8.2 建议反馈表
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'feedback_id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    type TINYINT NOT NULL COMMENT 'type:1-suggest 2-bug 3-optimize 4-other',
    module VARCHAR(50) DEFAULT NULL COMMENT 'module',
    content TEXT NOT NULL COMMENT 'content',
    images TEXT DEFAULT NULL COMMENT 'images json',
    contact VARCHAR(50) DEFAULT NULL COMMENT 'contact',
    device_info VARCHAR(255) DEFAULT NULL COMMENT 'device_info',
    app_version VARCHAR(20) DEFAULT NULL COMMENT 'app_version',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait 2-replied 3-adopted 4-closed',
    handler_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'handler_id',
    reply TEXT DEFAULT NULL COMMENT 'reply',
    reply_time DATETIME DEFAULT NULL COMMENT 'reply_time',
    is_public TINYINT NOT NULL DEFAULT 0 COMMENT 'is_public:0-no 1-yes',
    public_time DATETIME DEFAULT NULL COMMENT 'public_time',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    KEY idx_type (type),
    KEY idx_status (status),
    KEY idx_handler_id (handler_id),
    KEY idx_created_at (created_at),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='feedback';

-- 4.8.3 客服工单表
CREATE TABLE IF NOT EXISTS ticket (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ticket_id',
    ticket_no VARCHAR(32) NOT NULL COMMENT 'ticket_no',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    category TINYINT NOT NULL COMMENT 'category:1-consult 2-after_sale 3-suggest 4-complaint 5-other',
    priority TINYINT NOT NULL DEFAULT 1 COMMENT 'priority:1-low 2-medium 3-high 4-urgent',
    title VARCHAR(100) NOT NULL COMMENT 'title',
    content TEXT NOT NULL COMMENT 'content',
    images TEXT DEFAULT NULL COMMENT 'images json',
    contact VARCHAR(50) DEFAULT NULL COMMENT 'contact',
    status TINYINT NOT NULL DEFAULT 1 COMMENT 'status:1-wait_assign 2-processing 3-wait_confirm 4-completed 5-closed',
    assignee_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'assignee_id',
    assign_time DATETIME DEFAULT NULL COMMENT 'assign_time',
    process_content TEXT DEFAULT NULL COMMENT 'process_content',
    process_time DATETIME DEFAULT NULL COMMENT 'process_time',
    user_confirm TINYINT DEFAULT NULL COMMENT 'user_confirm:0-unsatisfied 1-satisfied',
    user_comment TEXT DEFAULT NULL COMMENT 'user_comment',
    close_time DATETIME DEFAULT NULL COMMENT 'close_time',
    close_user_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'close_user_id',
    source VARCHAR(20) DEFAULT NULL COMMENT 'source:app/h5/miniapp/web',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    update_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'update_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated_at',
    deleted_at DATETIME DEFAULT NULL COMMENT 'deleted_at',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ticket_no (ticket_no),
    KEY idx_user_id (user_id),
    KEY idx_category (category),
    KEY idx_status (status),
    KEY idx_assignee_id (assignee_id),
    KEY idx_priority (priority),
    KEY idx_created_at (created_at),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ticket';

-- 4.9.1 消息通知表
CREATE TABLE IF NOT EXISTS notification (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'notification_id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'user_id',
    type TINYINT NOT NULL COMMENT 'type:1-system 2-order 3-inquiry 4-activity 5-drug_remind',
    title VARCHAR(100) NOT NULL COMMENT 'title',
    content TEXT NOT NULL COMMENT 'content',
    data JSON DEFAULT NULL COMMENT 'data json',
    link_type VARCHAR(50) DEFAULT NULL COMMENT 'link_type:inquiry/order/prescription/webview',
    link_id VARCHAR(50) DEFAULT NULL COMMENT 'link_id',
    is_read TINYINT NOT NULL DEFAULT 0 COMMENT 'is_read:0-no 1-yes',
    read_time DATETIME DEFAULT NULL COMMENT 'read_time',
    push_status TINYINT NOT NULL DEFAULT 0 COMMENT 'push_status:0-not 1-success 2-failed',
    push_time DATETIME DEFAULT NULL COMMENT 'push_time',
    push_platform VARCHAR(20) DEFAULT NULL COMMENT 'push_platform:ios/android/harmony',
    expire_time DATETIME DEFAULT NULL COMMENT 'expire_time',
    create_user BIGINT UNSIGNED DEFAULT NULL COMMENT 'create_user',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    KEY idx_type (type),
    KEY idx_is_read (is_read),
    KEY idx_created_at (created_at),
    KEY idx_user_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='notification';

-- 5.10.1 操作日志表
CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'log_id',
    log_type TINYINT NOT NULL COMMENT 'log_type:1-login 2-operation 3-exception 4-audit',
    user_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'user_id',
    user_type TINYINT DEFAULT NULL COMMENT 'user_type',
    username VARCHAR(50) DEFAULT NULL COMMENT 'username',
    ip VARCHAR(50) DEFAULT NULL COMMENT 'ip',
    user_agent VARCHAR(500) DEFAULT NULL COMMENT 'user_agent',
    module VARCHAR(50) DEFAULT NULL COMMENT 'module',
    action VARCHAR(100) DEFAULT NULL COMMENT 'action',
    method VARCHAR(100) DEFAULT NULL COMMENT 'method',
    url VARCHAR(500) DEFAULT NULL COMMENT 'url',
    params TEXT DEFAULT NULL COMMENT 'params',
    result TEXT DEFAULT NULL COMMENT 'result',
    status TINYINT DEFAULT 1 COMMENT 'status:0-fail 1-success',
    error_msg TEXT DEFAULT NULL COMMENT 'error_msg',
    duration INT DEFAULT NULL COMMENT 'duration ms',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT 'trace_id',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create_time',
    PRIMARY KEY (id),
    KEY idx_user_id (user_id),
    KEY idx_log_type (log_type),
    KEY idx_module (module),
    KEY idx_create_time (create_time),
    KEY idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='sys_log';

-- 4.10.2 短信发送记录表
CREATE TABLE IF NOT EXISTS sms_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'log_id',
    mobile VARCHAR(20) NOT NULL COMMENT 'mobile',
    scene VARCHAR(20) NOT NULL COMMENT 'scene:login/register/findPwd/changeMobile',
    code VARCHAR(10) DEFAULT NULL COMMENT 'code',
    content VARCHAR(500) DEFAULT NULL COMMENT 'content',
    template_code VARCHAR(50) DEFAULT NULL COMMENT 'template_code',
    provider VARCHAR(20) DEFAULT NULL COMMENT 'provider:aliyun/tencent',
    provider_msg_id VARCHAR(100) DEFAULT NULL COMMENT 'provider_msg_id',
    status TINYINT NOT NULL DEFAULT 0 COMMENT 'status:0-sending 1-success 2-fail',
    error_msg VARCHAR(255) DEFAULT NULL COMMENT 'error_msg',
    send_time DATETIME DEFAULT NULL COMMENT 'send_time',
    expire_time DATETIME DEFAULT NULL COMMENT 'expire_time',
    verify_time DATETIME DEFAULT NULL COMMENT 'verify_time',
    verify_status TINYINT DEFAULT 0 COMMENT 'verify_status:0-not 1-verified 2-expired',
    ip VARCHAR(50) DEFAULT NULL COMMENT 'ip',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created_at',
    PRIMARY KEY (id),
    KEY idx_mobile (mobile),
    KEY idx_scene (scene),
    KEY idx_status (status),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='sms_log';
